name: PyPI Package Test

on:
  push:
    branches:
      - main

jobs:
  pypi-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atlas-ai[audio] requests pytest
      - name: Run e2e tests
        run: |
          python examples/object_detection_coco.py
          python examples/object_detection_yolo.py
          python examples/segmentation_coco.py
          python examples/hf_sink/audio_dataset.py
          python examples/hf_sink/audio_text_dataset.py
          python examples/hf_sink/coco_hf_dataset.py
          python examples/hf_sink/hf_nested_expansion_dataset.py
          python examples/hf_sink/image_dataset.py
          python examples/hf_sink/image_text_dataset.py
          python examples/hf_sink/multimodal_dataset.py
      - name: Run unit tests
        run: pytest tests/
